<script setup lang="ts">
import { Info, ShieldCheck } from "@lucide/vue";
import { computed, ref, watch } from "vue";
import { storeToRefs } from "pinia";
import { useReaderStore } from "@/features/reader/store";
import type { ProtocolError } from "@/domain/protocol";
import AccessibleDialog from "@/components/shared/AccessibleDialog.vue";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { t, type TranslationKey } from "@/locales";
const emit = defineEmits<{ exitPreview: [] }>();
const { inspection, isPreview, protocol } = storeToRefs(useReaderStore());
const integrityOpen = ref(false);
const blockingMessage = computed<TranslationKey | undefined>(() => { if (isPreview.value) return undefined; if (inspection.value.format === "invalid") return "reader.blocked.invalid"; if (inspection.value.signature === "mismatch") return "reader.blocked.mismatch"; if (inspection.value.signature === "unverified") return "reader.blocked.unverified"; return inspection.value.playable ? undefined : "reader.blocked.notPlayable"; });
watch(inspection, (value) => {
  integrityOpen.value =
    value.format === "invalid" || value.signature === "mismatch";
});
function errorSubject(error: ProtocolError): string { const directId = error.path.match(/(?:values|inputValues)\.([A-Za-z_][A-Za-z0-9_]*)/)?.[1]; if (directId !== undefined) return protocol.value?.variables.find((definition) => definition.id === directId)?.label ?? directId; const variableIndex = Number(error.path.match(/variables\.(\d+)/)?.[1]); return Number.isInteger(variableIndex) ? protocol.value?.variables[variableIndex]?.label ?? error.path : error.path || t("reader.frame.published"); }
function translatedError(error: ProtocolError): string { const path = error.path || t("reader.frame.published"); switch (error.code) { case "missing_input": case "missing_input_value": return t("reader.error.missingInput", { variable: errorSubject(error) }); case "invalid_input": case "invalid_variable_constraints": case "invalid_variable_default": return t("reader.error.invalidInput", { variable: errorSubject(error) }); case "invalid_duration": case "invalid_duration_variable": return t("reader.error.invalidDuration"); case "web_crypto_unavailable": return t("reader.error.webCrypto"); case "invalid_playback_session": return t("reader.error.invalidSession"); case "resource_limit": return t("reader.error.resourceLimit", { path }); case "invalid_image": return t("reader.error.invalidImage", { path }); case "formula_error": case "formula_test_failed": case "unknown_variable": case "non_numeric_variable": case "cyclic_dependency": case "missing_formula_test_case": case "missing_expected_value": return t("reader.error.formula", { path }); case "invalid_envelope_encoding": case "unrecognized_field": case "duplicate_section": case "duplicate_variable": return t("reader.error.structure", { path }); default: return t("reader.error.generic", { path, code: error.code }); } }
</script>
<template>
  <article class="signed-frame" :data-blocked="blockingMessage !== undefined" :aria-labelledby="protocol ? 'reader-protocol-title' : undefined">
    <header class="signed-frame-header"><div class="signed-frame-title"><p>{{ isPreview ? t("reader.frame.preview") : t("reader.frame.signed") }}</p><h2 id="reader-protocol-title">{{ protocol?.title ?? t("reader.frame.published") }}</h2></div><div class="integrity-actions"><div class="integrity-badges" :aria-label="t('reader.integrity.title')"><Badge :variant="inspection.format === 'valid' ? 'secondary' : 'destructive'">{{ inspection.format === "valid" ? t("reader.frame.validFormat") : t("reader.frame.invalidFormat") }}</Badge><Badge v-if="isPreview" variant="outline">{{ t("reader.frame.unsignedDraft") }}</Badge><Badge v-else :variant="inspection.signature === 'match' ? 'default' : inspection.signature === 'mismatch' ? 'destructive' : 'outline'">{{ inspection.signature === "match" ? t("reader.frame.signatureMatch") : inspection.signature === "mismatch" ? t("reader.frame.signatureMismatch") : t("reader.frame.signatureUnverified") }}</Badge><Badge :variant="inspection.playable ? 'secondary' : 'destructive'">{{ inspection.playable ? t("reader.frame.playable") : t("reader.frame.notPlayable") }}</Badge></div><Button type="button" size="sm" variant="outline" @click="integrityOpen = true"><ShieldCheck aria-hidden="true" />{{ t("reader.frame.integrityDetails") }}</Button></div></header>
    <dl class="frame-identifiers"><div><dt>{{ t("reader.integrity.fingerprint") }}</dt><dd>{{ inspection.protocolFingerprint ?? t("common.unavailable") }}</dd></div><div><dt>{{ t("reader.integrity.authorKeyId") }}</dt><dd>{{ inspection.keyId ?? t("common.unavailable") }}</dd></div></dl>
    <p class="identity-caveat"><Info aria-hidden="true" />{{ t("reader.frame.identityCaveat") }}</p>
    <div v-if="isPreview" class="preview-mode-banner" role="note"><div><p class="preview-mode-flags"><strong>{{ t("reader.frame.unsignedDraft") }}</strong><span aria-hidden="true">/</span><strong>{{ t("reader.frame.previewBadge") }}</strong><span aria-hidden="true">/</span><strong>{{ t("reader.preview.inMemory") }}</strong></p><p>{{ t("reader.preview.notice") }}</p></div><Button type="button" size="sm" variant="outline" @click="emit('exitPreview')">{{ t("reader.action.exitPreview") }}</Button></div><div v-else-if="blockingMessage" class="blocking-notice" role="alert">{{ t(blockingMessage) }}</div>
    <slot />
    <AccessibleDialog v-if="integrityOpen" id="integrity-sheet" :title="t('reader.integrity.title')" :confirm-label="t('reader.integrity.close')" :cancel-label="t('common.cancel')" @confirm="integrityOpen = false" @cancel="integrityOpen = false"><div class="reader-feature-scope"><p>{{ t("reader.integrity.overview") }}</p><dl class="integrity-grid"><div><dt>{{ t("reader.integrity.format") }}</dt><dd>{{ inspection.format === "valid" ? t("reader.frame.validFormat") : t("reader.frame.invalidFormat") }}</dd></div><div><dt>{{ t("reader.integrity.signature") }}</dt><dd>{{ isPreview ? t("reader.frame.unsignedDraft") : inspection.signature === "match" ? t("reader.frame.signatureMatch") : inspection.signature === "mismatch" ? t("reader.frame.signatureMismatch") : t("reader.frame.signatureUnverified") }}</dd></div><div><dt>{{ t("reader.integrity.playability") }}</dt><dd>{{ inspection.playable ? t("reader.frame.playable") : t("reader.frame.notPlayable") }}</dd></div><div><dt>{{ t("reader.integrity.fingerprint") }}</dt><dd>{{ inspection.protocolFingerprint ?? t("common.unavailable") }}</dd></div><div><dt>{{ t("reader.integrity.authorKeyId") }}</dt><dd>{{ inspection.keyId ?? t("common.unavailable") }}</dd></div></dl><section class="integrity-errors" aria-labelledby="integrity-checks-title"><h3 id="integrity-checks-title">{{ t("reader.integrity.checks") }}</h3><p v-if="inspection.errors.length === 0">{{ t("reader.integrity.noErrors") }}</p><ul v-else role="alert"><li v-for="error in inspection.errors" :key="`${error.path}:${error.code}`">{{ translatedError(error) }}</li></ul></section><p class="identity-caveat"><Info aria-hidden="true" />{{ t("reader.frame.identityCaveat") }}</p></div></AccessibleDialog>
  </article>
</template>
